root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - prettier
ignorePatterns:
  - '*.js'
